### ISSUE TITLE
Ignore front matter in markdown documents

### ISSUE THREAD

**Issue by ethernal** [mangecoeur/document-outline#19]
I hope I'm using right definition.

can you please ignore all texts that are included between front matter definition of the markdown document? I mean the part shown here

```markdown
---
title: 
author:
language: en-US
summary: 
date: "2017-03-23"
header-includes:
    - ...
papersize: a4wide
geometry: top=2cm, left=1.5cm, right=1.5cm, bottom=3cm, footskip=1cm
---
```

This is rendered in Outline and breaks the experience if you have a lot of information stored there. (I do).

**Comment by ethernal** [comment]
Could you please provide me some info on settext @mangecoeur? Is this still related to markdown grammar? If not you might check if document is md, markdown, etc (allow user to specify where to ignore setttext methods). That way there is no BC and I can keep front matter in 1 document.

This is quite important for me as my users will not remember about second document and it will be difficult for them.

**Comment by mangecoeur** [comment]
Settext is just a heading style, which looks like this

```
Header
------
```

(https://daringfireball.net/projects/markdown/basics)

As you can see, its a bit tricky to tell the difference between that and a yaml front matter. I would have to check if there are special rules that could make it possible to tell the difference between a header

**Comment by ethernal** [comment]
Hmm.. yeah but...

----- is AFTER the text whereas --- MUST have only 3 dashes and be the FIRST thing in the text so what I'd do before parsing any text:
Check if `---` (exactly 3 dashes) does not appear in the beginning of the file,
If it does in can ONLY be a front matter as a header would require to have a text before `----` appearance.

**Comment by mangecoeur** [comment]
OK, it seems some people also use headings similar to ReStructuredText (http://docutils.sourceforge.net/docs/user/rst/quickstart.html), and it seems this is allowed depending on the markdown flavour:

```
--------
Heading
--------
```

I guess I could try to check that if there is exactly 3 `---` before and after AND they are at the start of the file, then probably it's front matter. How easy that is will depend on how the commonmarkjs parser I use treats these cases (I was actually hoping there was a ready made yaml front matter plugin for it but seemingly not)

**Comment by salim-b** [comment]
> I guess I could try to check that if there is exactly 3 --- before and after AND they are at the start of the file, then probably it's front matter.

Just to note: The YAML metadata block (what you call _front matter_ here) [can either end with three `---` **or** with three `...`](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block). So don't forget that when implementing the parsing logic! 😉

**Comment by mangecoeur** [comment]
Righto, should be working in new version

**Comment by AndreasTusche** [comment]
Well, this is only working if your file has lines ending just in LF. It still does not work correctly for files using CRLF. Could you please revisit this case?
